stages:
  - lint
  - build
  - set-version

.deploy:
  stage: build    
  script:
    - echo "${ENV_FILE}" | envsubst > .env
    - docker build --build-arg CI_SERVER_HOST=$CI_SERVER_HOST --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -t "${PROJECT_NAME?}" -f "${DOCKERFILE?}" "${DOCKER_PROJECT_DIR?}"
    - docker stop "${PROJECT_NAME?}" || true
    - docker rm "${PROJECT_NAME?}" || true
    - docker run ${DOCKER_OPTS} -d -p ${EXT_PORT?}:${INT_PORT?} --name "${PROJECT_NAME}" "${PROJECT_NAME}"
  tags:
    - web3dev-dev  

linter:
  stage: lint
  image: node:16.15.1  
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - echo "$DEV_ENV" > .env
    - git config --global url."https://".insteadOf "git://"
    - git config --global url."https:///gitlab-ci-token:$CI_JOB_TOKEN@$CI_SERVER_HOST/".insteadOf "git@$CI_SERVER_HOST:"
    - yarn
    - yarn lint
    - yarn ts
  tags:
    - docker
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
    - if: '$CI_COMMIT_REF_NAME == "develop"'

deploy.dev:
  stage: build
  variables:
    ENV_FILE: '${DEV_ENV}'
    PROJECT_NAME: metzler-ui
    EXT_PORT: 3036
    INT_PORT: 3000
    DOCKERFILE: .docker/Dockerfile
    DOCKER_PROJECT_DIR: "."
  extends: .deploy
  only:
    - develop

deploy.release:
  stage: build
  variables:
    ENV_FILE: '${RELEASE_ENV}'
    PROJECT_NAME: metzler-ui-release
    EXT_PORT: 3035
    INT_PORT: 3000
    DOCKERFILE: .docker/Dockerfile
    DOCKER_PROJECT_DIR: "."
  extends: .deploy
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-rc\d+$/

release.set-version:  
  stage: set-version
  variables:
    GIT_STRATEGY: none    
  script:    
    - echo "Release "`date +%Y.%m.%d`" $CI_COMMIT_TAG" > /var/www/release/metzler/metzler-ui/version.txt    
  tags:
    - web3dev-dev
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-rc\d+$/
